### ISSUE TITLE
Why is %2f needed for defaultRabbitMQURI?

### ISSUE THREAD

**Issue by mihaitodor** [upfluence/sensu-client-go#11]
While writing some tests for sensu/config.go, I noticed that `defaultRabbitMQURI` has a funny value [here](https://github.com/upfluence/sensu-client-go/blob/master/sensu/config.go#L13). Is this intended?

**Comment by AlexisMontagne** [comment]
`%2f` is the url encoded value of `/`, `/` is the default vhost in RabbitMQ. 

The format of a RabbitMQ URI is `amqp://<user>:<pass>@<ip / DNS name>:<port>/<vhost>`

**Comment by mihaitodor** [comment]
Oh, interesting. I thought the root slash is implicit. Thanks!
