### ISSUE TITLE
High Availability RabbitMQ connection

### ISSUE THREAD

**Issue by mihaitodor** [upfluence/sensu-client-go#13]
I was wondering if you're considering adding the ability to connect to a high availability RabbitMQ cluster, as described [here](https://sensuapp.org/docs/latest/reference/rabbitmq.html#sensu-rabbitmq-configuration-examples-high-availability).

If you are, I might have a go at writing the code for it. I guess something similar to [this](https://github.com/sensu/sensu-transport/blob/master/lib/sensu/transport/rabbitmq.rb#L185) should fit the bill. It will also require having a way to define the hosts in the config json (not a big deal).

**Comment by AlexisMontagne** [comment]
You did a really good job about it 👍 

i will close this issue but feel free to submit some other pull requests to resolve the TODO you wrote in the PR.

**Comment by mihaitodor** [comment]
Thanks for merging the code and Happy New Year Alexis! :)

I've been caught up with other stuff in the mean time but I will submit more PRs soon.
