### ISSUE TITLE
this go client seems to crash the sensu server

### ISSUE THREAD

**Issue by gbolo** [upfluence/sensu-client-go#22]
running latest code from master seems to cause sensu server (0.27.1) to crash.

Client: commit-hash `fcd42765a2dcd27e6818ea641f588ac4cd3c084c`
Server: `sensu-0.27.1-2.el7.x86_64`

Sensu Server Log:
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.27.1/lib/sensu/server/process.rb:145:in `update_client_registry': undefined method `+' for nil:NilClass (NoMethodError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.27.1/lib/sensu/server/process.rb:185:in `block in setup_keepalives'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:162:in `block in on_delivery'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `each'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `exec_callback'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:294:in `handle_delivery'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:348:in `block in <class:Consumer>'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.27.1/lib/sensu/server/process.rb:31:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.27.1/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'
```

**Comment by mihaitodor** [comment]
Sensu devs need to learn that all user input is evil :) Without testing and studying in detail, I think they introduced this bug 7 days ago: https://github.com/sensu/sensu/commit/ea508bee76edd8b855c5c62cf2062ea4cbd8daf5

Could you please provide the definition of the check that you configured? I'm assuming it doesn't have a "subscriptions" attribute.

**Comment by gbolo** [comment]
Hi @mihaitodor 

Thanks for quick reply. I have tested like this:
```
git clone https://github.com/gbolo/dockerfiles.git
cd dockerfiles/sensu/
docker-compose up -d
docker logs sensu_sensu-server_1
```

You were right about the subscriptions, I don't have them in the config. I will add them in and try again

**Comment by gbolo** [comment]
I added the subscriptions but still get the error: https://github.com/gbolo/dockerfiles/blob/master/sensu/test/client/config/sensu-client-go.json

**Comment by mihaitodor** [comment]
OK, I'll do a bit more digging tomorrow and let you know what I find. Thanks for providing that docker compose setup. It's quite handy :)

**Comment by gbolo** [comment]
Hi @mihaitodor 

my apologies, I actually put the subscription on the `checks` instead of `client` section. It seems to work now :+1:

**Comment by gbolo** [comment]
no problem. I can open up a PR to mention this in documentation if you like. If not, I will close ticket.

**Comment by mihaitodor** [comment]
@gbolo Ah, awesome :) Glad it was a quick fix! It's my fault, because I said "check" instead of "client" :)

> I can open up a PR to mention this in documentation if you like.

I'll leave that up to you. I wonder if this can be replicated using the official Ruby client as well, in which case I'd consider opening a bug for the Sensu guys.

**Comment by gbolo** [comment]
@mihaitodor the docker-compose environment sets up both a ruby and go client. Seems like the ruby client does not have this problem (although, I didn't test an older version of ruby client). the ruby client config looks like this: [sensu-client-ruby.json](https://github.com/gbolo/dockerfiles/blob/master/sensu/test/client/config/sensu-client-ruby.json)

Great work on this go client btw! So much more secure and lean than having a ruby environment for the monitoring agent in my opinion. I will get to that PR later

**Comment by gbolo** [comment]
@mihaitodor created this PR #23 

Seems like the default ruby client always sends at least a default subscription of `client:name`. This PR should replicate this behaviour. Please be advised that this is both my **first ever PR** and near first ever exposure to `golang` :)

**Comment by mihaitodor** [comment]
@gbolo Cool! Thanks for digging into this issue :)

You should thank Alexis for this cool Go client. I'm just helping out with some minor enhancements (which I was forced to postpone a bit...) :)
